
-- create bookmark table
CREATE TABLE `bookmark-db`.`bookmark` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL` TEXT NOT NULL,
  `TITLE` VARCHAR(100) NOT NULL,
  `CREATED_DATE_TIME` DATETIME NOT NULL,
  `UPDATED_DATE_TIME` DATETIME NOT NULL,
  PRIMARY KEY (`ID`));
